[project]
name = "document"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "diagrams>=0.24.0",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.7.2",
]
